// <auto-generated />
using System;
using Medical_Appointments.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medical_Appointments.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medical_Appointments.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDate = new DateOnly(2026, 7, 1),
                            DoctorId = 1,
                            PatientId = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentDate = new DateOnly(2026, 8, 1),
                            DoctorId = 2,
                            PatientId = 2,
                            Status = "Pending"
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentDate = new DateOnly(2026, 9, 1),
                            DoctorId = 3,
                            PatientId = 3,
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Medical_Appointments.Entities.AppointmentMedical", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PerformedAt")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointment_Services");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            ServiceId = 1,
                            PerformedAt = new DateOnly(2026, 7, 1),
                            Quantity = 1
                        },
                        new
                        {
                            AppointmentId = 2,
                            ServiceId = 2,
                            PerformedAt = new DateOnly(2026, 8, 1),
                            Quantity = 1
                        },
                        new
                        {
                            AppointmentId = 3,
                            ServiceId = 3,
                            PerformedAt = new DateOnly(2026, 9, 1),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Medical_Appointments.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            FirstName = "Maciej",
                            LastName = "TezNowak",
                            Phone = "423456789",
                            Specialization = "Kardiologia"
                        },
                        new
                        {
                            DoctorId = 2,
                            FirstName = "Adam",
                            LastName = "Nowak",
                            Phone = "523456789",
                            Specialization = "TezNic"
                        },
                        new
                        {
                            DoctorId = 3,
                            FirstName = "Anna",
                            LastName = "Kowalska",
                            Phone = "623456789",
                            Specialization = "Nic"
                        });
                });

            modelBuilder.Entity("Medical_Appointments.Entities.Medical", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ServiceId");

                    b.ToTable("Medical_Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Description = "bla bla bla",
                            DurationInMinutes = 90,
                            Name = "Zabieg1",
                            Price = 100m
                        },
                        new
                        {
                            ServiceId = 2,
                            Description = "bla bla bla",
                            DurationInMinutes = 120,
                            Name = "Zabieg3",
                            Price = 200m
                        },
                        new
                        {
                            ServiceId = 3,
                            Description = "bla bla bla",
                            DurationInMinutes = 30,
                            Name = "Zabieg3",
                            Price = 300m
                        });
                });

            modelBuilder.Entity("Medical_Appointments.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "123456789"
                        },
                        new
                        {
                            PatientId = 2,
                            DateOfBirth = new DateTime(2000, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            LastName = "Kowalska",
                            Phone = "223456789"
                        },
                        new
                        {
                            PatientId = 3,
                            DateOfBirth = new DateTime(2000, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bob",
                            LastName = "Nowak",
                            Phone = "323456789"
                        });
                });

            modelBuilder.Entity("Medical_Appointments.Entities.Appointment", b =>
                {
                    b.HasOne("Medical_Appointments.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medical_Appointments.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Medical_Appointments.Entities.AppointmentMedical", b =>
                {
                    b.HasOne("Medical_Appointments.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentMedicals")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medical_Appointments.Entities.Medical", "Medical")
                        .WithMany("AppointmentMedicals")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Medical");
                });

            modelBuilder.Entity("Medical_Appointments.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentMedicals");
                });

            modelBuilder.Entity("Medical_Appointments.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Medical_Appointments.Entities.Medical", b =>
                {
                    b.Navigation("AppointmentMedicals");
                });

            modelBuilder.Entity("Medical_Appointments.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
